### ISSUE TITLE
How to synchronize flaps position with time and weather

### ISSUE THREAD

**Issue by nickzocchi** [barlowtj48/flipclock#1]
Hi! First of all, great project! I think it looks really cool and it's a fun thing to print or to gift.

That said, I'm having a bit of an hard time trying to synchronize the position of the flaps with the time and the weather symbols.
I tried assembling everything together, then holding the button for 10s to bring the flaps to their resting state, marking this position with 0 and starting the script again but the time shown is not what I expected.
Is the resting state meant to be all blank on flaps or the number zero?
Also, if the Pi loses power (and so the motors) when I turn on the clock again, it obviously resets and shows the incorrect numbers, is there a solution for this?

Thank you so much for the project!

**Comment by barlowtj48** [comment]
Thanks for your interest in the clock!

The script starts outputting the time immediately after it starts. This is assuming that the flaps are all at 0000. The order of the flaps are as follows:
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, where A is blank, and B, C, D, are weather icons. 

When the clock is paused, holding the button for a short time (less than 10s), it goes to AAAA (all blank), however holding for 10s will bring the clock back to it's fully power-off state of 0000. If you know how to change the script, then this can also be done one flap at a time, for example `Output("4000")` if you need to rotate the first flap 4 times. After this function be sure to add `quit()` so that it does not continue to output the time. 

Hope this helps.
